version: '3.9'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
      POSTGRES_DB: "chat_app_db"
    ports:
    - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data